on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Kill old FastAPI process
      run: |
        fuser -k 8080/tcp || true

    - name: Run FastAPI Demo
      run: RUNNER_TRACKING_ID="" && (nohup python src/App.py > RaspberryPiApi.log 2>&1 &)

