on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3

    - name: Remove existing Docker container if present
      run: |
        docker rm -f raspberrypiapi || true
      
    - name: Build Docker image
      run: docker build -t raspberrypiapi .

    - name: Run Docker container
      run: docker run -d -p 8080:8080 --name raspberrypiapi raspberrypiapi

